/**
 * A collection of pure, stateless utility functions for working with component metadata.
 * These functions can be safely imported by any module without creating dependencies
 * on stateful manager instances.
 */

import * as Schema from './ComponentSchema.js'

/**
 * Gets an array of component type IDs from a bitmask.
 * The returned array is implicitly sorted because it's generated by iterating
 * through type IDs in ascending order.
 * @param {bigint} mask - The bitmask to resolve.
 * @returns {number[]} An array of component type IDs.
 */
export function getComponentTypesFromMask(mask) {
	const types = []
	for (let i = 0; i < Schema.nextComponentTypeID; i++) {
		if ((mask & Schema.componentBitFlags[i]) !== 0n) types.push(i)
	}
	return types
}