import fs from 'fs/promises';
import path from 'path';
import * as babel from '@babel/core';
import extractSchedulePlugin from './babel-plugin-extract-schedule.js';

const systemsPath = path.resolve(process.cwd(), 'app/client/Systems');
const outputPath = path.resolve(process.cwd(), 'dist/systems');
const registryFilePath = path.join(outputPath, 'parallelSystemLogics.js');
const cacheFilePath = path.join(outputPath, '.cache.json');

/**
 * Finds all system files recursively in the given directory.
 * @param {string} dir - The directory to search.
 * @returns {Promise<string[]>} A list of absolute file paths.
 */
async function findSystemFiles(dir) {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    const files = await Promise.all(entries.map(async (entry) => {
        const res = path.resolve(dir, entry.name);
        if (entry.isDirectory()) {
            return findSystemFiles(res);
        }
        return res.endsWith('.js') ? res : null;
    }));
    return files.flat().filter(Boolean);
}

/**
 * The main function to transpile all systems.
 */
async function transpileAllSystems() {
    console.log('[Transpiler] Checking for system changes...');
    const systemFiles = await findSystemFiles(systemsPath);
    const parallelSystems = [];
    let hasChanges = false;

    await fs.mkdir(outputPath, { recursive: true });

    let oldCache = {};
    try {
        oldCache = JSON.parse(await fs.readFile(cacheFilePath, 'utf-8'));
    } catch (e) {
        // Cache file doesn't exist or is invalid, will build everything.
        console.log('[Transpiler] No cache found, performing full build.');
        hasChanges = true;
    }
    const newCache = {};

    for (const file of systemFiles) {
        const stats = await fs.stat(file);
        const cachedEntry = oldCache[file];

        if (cachedEntry && cachedEntry.mtime === stats.mtime.getTime()) {
            // File is unchanged, use cached metadata.
            newCache[file] = cachedEntry;
            if (cachedEntry.isParallel) {
                parallelSystems.push(cachedEntry);
            }
            continue;
        }

        // File is new or modified, transpile it.
        hasChanges = true;
        const sourceCode = await fs.readFile(file, 'utf-8');
        const result = await babel.transformAsync(sourceCode, {
            plugins: [extractSchedulePlugin],
            sourceType: 'module',
            filename: file,
        });

        const metadata = { 
            mtime: stats.mtime.getTime(),
            isParallel: result.metadata.isParallel || false,
            systemName: result.metadata.systemName,
            dependencies: result.metadata.dependencies,
        };

        newCache[file] = metadata; 

        if (metadata.isParallel) {
            const { systemName } = metadata;
            const workerFileName = `${systemName}.worker.js`;
            const workerFilePath = path.join(outputPath, workerFileName);

            await fs.writeFile(workerFilePath, result.code);
            parallelSystems.push(metadata);
            console.log(`[Transpiler] Extracted parallel logic for: ${systemName}`);
        }
    }

    if (hasChanges) {
        await generateLogicRegistry(parallelSystems);
        await fs.writeFile(cacheFilePath, JSON.stringify(newCache, null, 2));
        console.log(`[Transpiler] System transpilation finished. ${parallelSystems.length} parallel systems processed.`);
    } else {
        console.log('[Transpiler] No changes detected. Build is up-to-date.');
    }
}

/**
 * Generates the parallelSystemLogics.js file.
 * @param {Array<{systemName: string, dependencies: string[]}>} systems
 */
async function generateLogicRegistry(systems) {
    let content = `// This file is auto-generated by the system transpiler. Do not edit manually.\n\n`;
    
    systems.forEach(({ systemName }) => {
        content += `import { schedule as ${systemName}_schedule } from './${systemName}.worker.js';\n`;
    });

    content += `\nexport const logicRegistry = {\n`;
    systems.forEach(({ systemName, dependencies }) => {
        content += `    "${systemName}": { logic: ${systemName}_schedule, dependencies: ${JSON.stringify(dependencies)} },\n`;
    });
    content += `};\n`;

    await fs.writeFile(registryFilePath, content);
}

transpileAllSystems().catch(console.error);